# Credits to @Scighost from Starward for his contributions!
name: Build-Canary
#run-name: Canary Build for ${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches:
        - 'main'
    paths-ignore:
        - '**.md'
        - 'Hi3Helper.Core/Lang/**.json'
        - 'Docs/**'
        - '**/packages.lock.json'
  pull_request:
    branches-ignore:
      - 'stable'
      - 'preview'
      - 'translations_**'
    paths-ignore:
        - '**.md'
        - 'Hi3Helper.Core/Lang/**.json'
        - 'Docs/**'
        - '**/packages.lock.json'
#  schedule:
#    - cron: '0 0 * * 0' # At 00:00 on Sunday

env:
  DOTNET_INSTALL_DIR: '.\.dotnet' 
  DOTNET_VERSION: '9.0.2xx'
  DOTNET_QUALITY: 'ga'
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    # runs-on: [self-hosted, linux]
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug] # No need to distribute Debug builds
        platform: [x64]
        framework: [net9.0-windows10.0.22621.0]

    env:
      Configuration: ${{ matrix.configuration }}
      Platform: ${{ matrix.platform }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        dotnet-quality: ${{ env.DOTNET_QUALITY }}
        cache: true
        cache-dependency-path: CollapseLauncher/packages.lock.json

    - name: Update .NET workload
      run: dotnet workload update

    - name: Build
      run: |
        dotnet publish CollapseLauncher -c ${{matrix.Configuration}} -p:PublishProfile=Publish-DebugCIRelease -p:PublishDir=".\debug-build\"
          
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
          name: collapse_${{ matrix.platform }}-${{ matrix.configuration }}_${{ matrix.framework }}_${{ github.sha }}
          path: ./CollapseLauncher/debug-build/
          compression-level: 9


